maintenance.sh: added option to show deleted files between two snapshots

diff --git a/roles/maintenance/templates/mpserver-maintenance.sh.j2 b/roles/maintenance/templates/mpserver-maintenance.sh.j2
--- a/roles/maintenance/templates/mpserver-maintenance.sh.j2
+++ b/roles/maintenance/templates/mpserver-maintenance.sh.j2
@@ -238,8 +238,52 @@ snapshot_all()
     log "\n\nCreate snapshots of all subvolumes..."
     # create btrfs snapshots of all subvolumes
     $BTRBK_CMD --preserve snapshot &>> $LOGFILE
+
+    local btrbk_exit=$?
+    if [ $btrbk_exit -ne 0 ]; then
+        log "\n\n###################################################################"
+        log "ERROR!! btrbk failed to create snapshot of all subvolumes with exit code: $btrbk_exit"
+        log "###################################################################\n\n"
+        EMAIL=true      # always notify for error!
+        LOG_TYPE="ERROR"
+    fi
+
+    show_deleted_files Daten
+    # show_deleted_files Backups
+    show_deleted_files Archiv
+    show_deleted_files Filme
+    show_deleted_files Musik
+
 }
 
+show_deleted_files()
+{
+    # shows all deleted files between two snapshots
+    log  # empty line
+
+    if [[ $# -lt 1 ]]; then
+        log "ERROR: show_deleted_files() expects exactly one argument!"
+        return 1
+    fi
+
+    last_two_snapshots=$(find {{ mount_nas_drive }}/snapshots/"$1" -maxdepth 1 -name "${1}*" | tail -n 2)
+    parent_snapshot=$(echo "$last_two_snapshots" | head -n 1)
+    current_snapshot=$(echo "$last_two_snapshots" | tail -n 1)
+
+    if [ -z "$parent_snapshot" ] || [ -z "$current_snapshot" ]; then
+        log "Could not detect last snapshots for $1!"
+        return 1
+    fi
+
+    if [[ $current_snapshot != *$(date +%Y%m%d)* ]]; then
+        log "No current snapshot could be found! Last snapshot is $current_snapshot. Skipping compare."
+        return 1
+    fi
+
+    log "Comparing snapshots:\n\t$parent_snapshot (parent)\n\t$current_snapshot (current)"
+    log "\nDeleted files:"
+    log "$(btrfs send --no-data -p "$parent_snapshot" "$current_snapshot" | btrfs receive --dump | grep unlink)"
+}
 
 run_backup()
 {
@@ -287,6 +331,8 @@ daily()
         sync
         umount $MOUNT_BKP_DRIVE
     fi
+
+    show_deleted_files Daten
 }
 
 weekly()
@@ -491,7 +537,10 @@ case $1 in
         DRYRUN=true
         EMAIL=false
         echo "Test mode, no email + dryrun"
-        update_containers
+        show_deleted_files Daten
+        show_deleted_files Archiv
+        show_deleted_files Filme
+        show_deleted_files Musik
         ;;
     *)
         usage
